export const GET_IMAGES = 'GET_IMAGES'
export const SET_IMAGES = 'SET_IMAGES'
export const SET_WINNER = 'SET_WINNER'
export const GET_LIST = 'GET_LIST'
export const SET_LIST = 'SET_LIST'
export const RANDOM_IMAGE = 'RANDOM_IMAGE'