export const GET_IMAGES = 'GET_IMAGES'
export const SET_IMAGES = 'SET_IMAGES'
export const GET_LIST = 'GET_LIST'
export const SET_LIST = 'SET_LIST'
export const RANDOM_BREEDS = 'RANDOM_BREEDS'
export const RIGHT_ANSWER = 'RIGHT_ANSWER'
export const WRONG_ANSWER = 'WRONG_ANSWER'
export const NEXT_QUESTION = 'NEXT_QUESTION'