export const SET_IMAGES = 'SET_IMAGES'
export const SET_WINNER = 'SET_WINNER'
export const SET_LIST = 'SET_LIST'
export const RANDOM_BREEDS = 'RANDOM_BREEDS'
export const RIGHT_ANSWER = 'RIGHT_ANSWER'
export const WRONG_ANSWER = 'WRONG_ANSWER'
export const SET_PERFORMANCE = 'SET_PERFORMANCE'